title = "Welcome to Chiragk Site"
baseURL = "https://chiragkhabaria.github.io/chiragk/"

languageCode = "en-us"
defaultContentLanguage = "en-us"

SectionPagesMenu = "Main"
theme = "bleak"
publishDir = "docs"
paginate = 6
uglyurls = true
pygmentsCodeFences = true
pygmentsStyle = "vs"

enableEmoji = true

[blackfriday] 
     hrefTargetBlank=true

removePathAccents = false
preserveTaxonomyNames = false

[taxonomies]
  tag = "tags"
  

#outputFormats:
 # RSS:
  #  mediatype: "application/rss"
  #  baseName: "rss"

[params]
  mainSections = ["posts", "podcasts"]
  Description = "El podcast en el que hablamos sobre desarrollo de aplicaciones, operaciones de sistemas informáticos y todo lo relacionado con la filosofía DevOps"
  Subtitle = "El podcast en el que hablamos sobre desarrollo de aplicaciones, operaciones de sistemas informáticos y todo lo relacionado con la filosofía DevOps"

  cover = "/images/cover.jpg"
  logo = "/images/logo2.png"
  icon = "/images/edyo-icon.png"

  license = "<a target=\"_blank\" href=\"http://creativecommons.org/licenses/by-nc-sa/3.0/deed.es_ES\"><i class=\"fab fa-creative-commons\"></i> BY-NC-SA 3.0</a>"

  cookiesNoticePage = "politica-cookies.html"
  cookiesNoticeMessage = "Esta web utiliza cookies de terceros para mejorar la experiencia de la web y recopilar datos de uso. Si continúas navegando, consideramos que aceptas su uso."

  showToc = false

  #googleAnalyticsUserID: "UA-25613214-1"

  disqus = "edyo"
  twitter = "entredevyops"
  LinkedIn = "EntreDevYOps"
  github = "edyo"
  telegram = "entredevyops"

  [podcast]
    audioBaseUrl = "http://podcast.edyo.es/podcast/"

[[menu.main]]
    Name = "Episodios podcast"
    URL = "/podcasts.html"
    Identifier = "podcasts"
    Weight = 10
[[menu.main]]
    Name = "Artículos"
    URL = "/posts.html"
    Identifier = "posts"
    Weight = 20
[[menu.main]]
    Name = "Equipo"
    URL = "/equipo.html"
    Identifier = "team"
    Weight = 30
[[menu.main]]
    Name = "Código de conducta"
    URL = "/codigo-conducta.html"
    Identifier = "coc"
    Weight = 50

[[menu.subscription]]
    Name = "Podcast RSS"
    URL = "https://feedpress.me/edyo"
    Identifier = "feed-rss-podcasts"
    Weight = 10
[[menu.subscription]]
    Name = "Podcast en iVoox"
    URL = "https://www.ivoox.com/podcast-entre-dev-y-ops-podcast_sq_f1112910_1.html"
    Identifier = "ivoox"
    Weight = 20
[[menu.subscription]]
    Name = "Podcast en iTunes"
    URL = "https://itunes.apple.com/es/podcast/entredevyops-podcast/id866788492"
    Identifier = "itunes"
    Weight = 30
[[menu.subscription]]
    Name = "Web RSS"
    URL = "/rss.xml"
    Identifier = "feed-rss"
    Weight = 40
