title = "The blog of Chirag Khabaria "
baseURL = "https://chiragkhabaria.github.io/chiragk/"

languageCode = "en-us"
defaultContentLanguage = "en-us"

SectionPagesMenu = "Main"
theme = "bleak"
publishDir = "docs"
paginate = 6
uglyurls = true
pygmentsCodeFences = true
pygmentsStyle = "vs"

enableEmoji = true

[blackfriday] 
     hrefTargetBlank=true

removePathAccents = false
preserveTaxonomyNames = false

[taxonomies]
  tag = "tags"
  

#outputFormats:
 # RSS:
  #  mediatype: "application/rss"
  #  baseName: "rss"

[params]
  mainSections = ["posts", "podcasts"]
  Description = ""
  Subtitle = "Mind may travel through past, future and different horizons but the truth is we are trap in this moment, so let this moment be blissful. "

  cover = "/images/cover1.jpg"
  logo = "/images/logo2.png"
  icon = "/images/edyo-icon.png"

  license = "<a target=\"_blank\" href=\"http://creativecommons.org/licenses/by-nc-sa/3.0/deed.es_ES\"><i class=\"fab fa-creative-commons\"></i> BY-NC-SA 3.0</a>"

  cookiesNoticePage = "politica-cookies.html"
  cookiesNoticeMessage = "Esta web utiliza cookies de terceros para mejorar la experiencia de la web y recopilar datos de uso. Si continúas navegando, consideramos que aceptas su uso."

  showToc = false

  googleAnalyticsUserID= "UA-54044497-6"

  disqus = "chiragk-com"
  twitter = "chiragkhabaria"
  linkedIn = "chiragkhabaria"
  github = "chiragkhabaria"
  instagram = "chiragkhabaria"

  [podcast]
    audioBaseUrl = "http://podcast.edyo.es/podcast/"

[[menu.main]]
    Name = "Episodios podcast"
    URL = "/podcasts.html"
    Identifier = "podcasts"
    Weight = 10
[[menu.main]]
    Name = "Artículos"
    URL = "/posts.html"
    Identifier = "posts"
    Weight = 20
[[menu.main]]
    Name = "Equipo"
    URL = "/equipo.html"
    Identifier = "team"
    Weight = 30
[[menu.main]]
    Name = "Código de conducta"
    URL = "/codigo-conducta.html"
    Identifier = "coc"
    Weight = 50
